# frozen_string_literal: true

require 'tataru/rom_reader'
require 'tataru/base_resource'
require 'tataru/base_resource_desc'
require 'tataru/resource_dsl'
require 'tataru/representation'
require 'tataru/resolver'
require 'tataru/top_dsl'
require 'tataru/flattener'
require 'tataru/create_subroutines'
require 'tataru/delete_subroutines'
require 'tataru/update_subroutines'
require 'tataru/subroutine_compiler'
require 'tataru/init_hash_compiler'
require 'tataru/sub_planner'
require 'tataru/compiler'
require 'tataru/quest'
require 'tataru/resource_type_pool'
require 'tataru/instruction_hash'
require 'tataru/instruction'
require 'tataru/memory'
require 'tataru/runner'
